repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Replace with the latest version of black
    hooks:
      - id: black
        language_version: python3.11  # Replace with your Python version
        files: ^backend/.*\.py$

