name: Compile LaTeX Document

on:
  push:
    paths:
      - '**.tex'

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container: 
      image: dxjoke/tectonic-docker  # Docker image with LaTeX

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Compile LaTeX Document
      run: latexmk -pdf report/report.tex

    - name: Upload PDF to Repository
      uses: actions/upload-artifact@v3
      with:
        name: report-pdf
        path: report/report.pdf

    - name: Commit PDF to Repository
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add report/report.pdf
        git commit -m "Automatically compiling .tex report to pdf"
        git push
